services:
  gdrive-service:
    build: .
    container_name: visor-xr-gdrive-service
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - PORT=4000
      - NODE_ENV=production
